version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - 3000:5173
    volumes:
      - ./frontend:/app
    depends_on:
      - app

  app:
    build:
      context: ./backend
    container_name: laravel_app
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: news
      MYSQL_ROOT_PASSWORD: 'Phone03#'
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
